# Generated by Django 3.2.6 on 2021-08-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('empresa', models.CharField(max_length=60)),
                ('descricao', models.TextField()),
                ('salario', models.FloatField()),
                ('area', models.CharField(max_length=60)),
                ('linguagem', models.CharField(max_length=60)),
                ('framework', models.CharField(max_length=60)),
                ('disponivel', models.BooleanField(default=False)),
                ('disponivel_ate', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
