# Generated by Django 3.2.6 on 2021-08-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='area',
            field=models.CharField(choices=[('frontend', 'Front-end'), ('backend', 'Back-end'), ('devops', 'Dev-ops'), ('mobile', 'Mobile'), ('outro', 'Outro')], max_length=60, verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='disponivel',
            field=models.BooleanField(default=False, verbose_name='Disponível'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='disponivel_ate',
            field=models.DateTimeField(verbose_name='Disponível Até'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='empresa',
            field=models.CharField(max_length=60, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='framework',
            field=models.CharField(max_length=60, verbose_name='Framework'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='linguagem',
            field=models.CharField(max_length=60, verbose_name='Linguagem'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='nome',
            field=models.CharField(max_length=60, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='salario',
            field=models.FloatField(verbose_name='Salário'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
